#!/bin/bash
#!/bin/bash
#SBATCH -J Adcirpolate-OW-HSOFS
#SBATCH -A TG-DMS080016N
#SBATCH -o adcirp.o%j
#SBATCH -e adcirp.o%j
#SBATCH -p skx-normal
#SBATCH -N 3
#SBATCH -n 118
#SBATCH -t 08:00:00

 
#SBATCH --mail-user=apoisso@ncsu.edu
#SBATCH --mail-type=begin   # email me when the job starts
#SBATCH --mail-type=end     # email me when the job finishes

# run the executable
date
ibrun mem_affinity ./adcirpolate
date

