#! /bin/bash
#! /bin/bash
#SBATCH -J Matthew-OW-6days
#SBATCH -A TG-DMS080016N
#SBATCH -o adcprep.o%j
#SBATCH -e adcprep.e%j
#SBATCH -p skx-dev
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 00:30:00

#SBATCH --mail-user=apoisso@ncsu.edu
#SBATCH --mail-type=begin        # email me when the job starts
#SBATCH --mail-type=end          # email me when the job finishes

date
./adcprep --np 118 --partmesh
./adcprep --np 118 --prepall
date
